### ISSUE TITLE
Research whether welcome messages are still supported

### ISSUE THREAD

**Issue by maciekmm** [maciekmm/messenger-platform-go-sdk#13]
https://github.com/maciekmm/messenger-platform-go-sdk/blob/master/welcomemessage.go

**Comment by zxr90** [comment]
Hi, I just used your library and tested this. This API doesn't seem to work.

Side Question: Using your example, it seems like I can only get messages I (page creator) sent to the page. Using another fb account, I don't get the echo message back. Not sure if you can help me with this.

**Comment by maciekmm** [comment]
@zxr90 Thanks for your feedback.

AFAIK: If your bot is not approved, you will only get messages from page admins delivered to your webhook.

**Comment by zxr90** [comment]
@maciekmm ohh i see. Thanks for the valuable information and awesome library!
