### ISSUE TITLE
Event ID can be string or int

### ISSUE THREAD

**Issue by marselester** [maciekmm/messenger-platform-go-sdk#2]
Hi Maciej,

Unfortunately Facebook is not consistent with entry IDs. For messages it uses strings `{"object":"page","entry":[{"id":"123",`, but for postbacks ints `{"object":"page","entry":[{"id":123,`.

Not sure what would be a proper way to handle that, I use `json.Number` and hope Facebook migrates to strings eventually.

```go
type Event struct {
	ID   json.Number `json:"id"`
	Time int64       `json:"time"`
}
```

**Comment by maciekmm** [comment]
@marselester thanks for bringing this up.
I think implementing json.Unmarshaler to handle conversion would be a better idea. If facebook finally decides to switch to strings as they plan it'd be easy to just get rid.
