### ISSUE TITLE
SetWelcomeMessage returns a 400

### ISSUE THREAD

**Issue by EwanValentine** [maciekmm/messenger-platform-go-sdk#7]
Hi there! Me again :)

When I attempt to set a welcome message, like...

```
err := mess.SetWelcomeMessage(&messenger.Message{
    Text: "Hello!",
})

if err != nil {
    log.Fatal(err)
}
```

I get an error `Invalid status code`.

So I had a little dig into the code and I've noticed in `welcomemessage.go` 

```
var welcomeMessage = ctaBase{
	SettingType: "setting_type",
	ThreadState: "new_thread",
}
```

According to the [docs](https://developers.facebook.com/docs/messenger-platform/send-api-reference#welcome_message_configuration), that should be... 

```
var welcomeMessage = ctaBase{
	SettingType: "call_to_actions",
	ThreadState: "new_thread",
}
```

However I tried changing this and got the same result.

**Comment by EwanValentine** [comment]
Submitted a PR for the issue I found, it doesn't solve the 400 still unfortunately :(

**Comment by maciekmm** [comment]
@EwanValentine I will investigate further, thanks for reporting and for PR.
